name: Docker Image CI for GitHub Container Registry

on:
  push:
    branches: [ main ]

jobs:
  build_and_publish:
  runs-on: ubuntu-latest
  steps:
    - user: actions/checkout@v3
    - name: Build and push the docker image
      run: |
        docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
        docker build -t ghcr.io/${{ github.repository }}:latest .
        docker push ghcr.io/${{ github.repository }}:latest